### ISSUE TITLE
INFOGRAFÍA DE LIBRERÍAS

### ISSUE THREAD

**Issue by IsaHuerta23** [SistemasTecTlaxiaco/infografia-de-las-librerias-IsaHuerta23#2]
![LIBRERÍA](https://user-images.githubusercontent.com/79929235/114480555-5f536f00-9bc8-11eb-83a2-25bc60e48bc0.png)

**Comment by DuilioAquino10** [comment]
Calificación 20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
